### ISSUE TITLE
master code gives  "undefined symbol: CheckFunctionValidatorAccess"

### ISSUE THREAD

**Issue by karatasse** [petere/plsh#7]
Hello Peter,

I am using EnterpriseDB 9.3.1.3 (on Red Hat 4.1.2-52) and I installed this project by using master branch; after installation, when I tried to create plsh extension, I got error:

```
# CREATE EXTENSION plsh;
ERROR:  could not load library "/opt/PostgresPlus/9.3AS/lib/plsh.so": /opt/PostgresPlus/9.3AS/lib/plsh.so: undefined symbol: CheckFunctionValidatorAccess
```

After some inspections I could not find any solution. 

Thanks

PS. I downloaded 1.20130823 version (plsh-1.20130823.tar.gz) and installed it; it works like a charm.

**Comment by petere** [comment]
You need to use PostgreSQL 9.3.3 or later (or the equivalent EnterpriseDB version). The missing symbol is related to a security fix, so an update is recommended. Otherwise, use an older version of PL/sh, as you have discovered.
